# swagger.yml

openapi: 3.0.0
info:
  title: "Student Interactions REST API"
  description: "An API for residence life to track interactions"
  version: "1.0.0"

servers:
  - url: "/api"

paths:
  /interactions:
    get:
      operationId: "interactions.read_all"
      tags:
        - "Interactions"
      summary: "Read the list of interactions"
      responses:
        "200":
          description: "Successfully read interaction list"